---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nginxpod.com
  resources:
  - nginxpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginxpod.com
  resources:
  - nginxpods/finalizers
  verbs:
  - update
- apiGroups:
  - nginxpod.com
  resources:
  - nginxpods/status
  verbs:
  - get
  - patch
  - update
