# This rule is not used by the project calculate itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to culate.com.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: calculate
    app.kubernetes.io/managed-by: kustomize
  name: calculate-viewer-role
rules:
- apiGroups:
  - culate.com.my.domain
  resources:
  - calculates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - culate.com.my.domain
  resources:
  - calculates/status
  verbs:
  - get
