---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - culate.com.my.domain
  resources:
  - calculates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - culate.com.my.domain
  resources:
  - calculates/finalizers
  verbs:
  - update
- apiGroups:
  - culate.com.my.domain
  resources:
  - calculates/status
  verbs:
  - get
  - patch
  - update
